language: ruby
rvm:
  - 2.2.0
before_script:
  - psql -c 'create database workshops_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - RAILS_ENV=test bundle exec rake spec
addons:
  postgresql: '9.3'
